name: Build

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Testing
    types:
      - completed
    branches:
      - main

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: |
          npm run build -w packages/mdx
      - name: Publish packages
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm run publish:packages
      - name: Build on EAS
        run: |
          npm install
          npm run cd
